#line 2 "alex.c"

#line 4 "alex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 154
#define YY_END_OF_BUFFER 155
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[483] =
    {   0,
        0,    0,  155,  153,    1,    3,  153,  135,  141,  142,
      133,  131,  145,  132,  143,  134,  149,  144,  146,  153,
      150,   32,   38,  150,   35,  150,  150,   34,   43,   29,
       28,   30,  139,  140,  150,  150,  150,  150,  150,  150,
      150,  150,  150,  150,  150,  150,  150,  150,  150,  150,
      150,  150,  150,  150,  150,  137,  138,    1,    0,  136,
      147,  149,    0,  149,  149,    0,  148,  150,  150,  150,
       39,   36,   37,   33,   31,   40,  150,  150,  150,  150,
      150,  150,   78,  150,   55,  150,  150,  150,  150,  150,
       54,  150,  150,  150,  150,  150,  150,  150,  150,  150,

      150,  150,  150,  150,  150,  150,  150,   59,   58,   68,
       67,  150,  150,  150,  150,  150,   65,   53,  150,   57,
      150,   52,  150,   51,  150,  150,  150,  150,  150,  150,
      150,  150,  150,  150,  150,  150,  150,  150,  150,  150,
      150,   14,   15,  150,  150,   16,  150,  150,  150,  151,
        0,    2,  149,   42,   41,   79,  121,   82,  150,  150,
      150,  150,  150,  126,  150,  150,  150,  150,  150,  150,
      150,    8,  150,  150,  150,  150,  150,  120,  150,  150,
      150,  129,  150,  150,   86,  150,  150,    9,  150,  127,
      150,  150,    6,   47,   48,   66,  118,  150,  150,  150,

      150,  150,  150,  150,  150,   24,  150,  150,  150,  150,
      150,  150,  150,  150,  150,  119,  150,  150,  150,  150,
      130,  150,  150,  122,  150,  150,  150,  150,  150,  150,
      109,  150,  150,   77,  150,  150,  150,  150,  150,  150,
      150,  150,  150,  150,  150,  150,  125,   61,  150,  150,
      150,   88,  150,   70,  150,  150,  150,   81,  150,  150,
      150,  150,  150,   95,  150,  150,   69,  150,  150,  150,
      112,  150,  150,  150,  150,   21,  150,  128,  150,  117,
      150,   60,   94,  150,    7,  150,  150,  150,  150,  150,
      150,  116,  105,  150,  150,  150,  150,  150,  150,   17,

      150,  150,  150,    4,  150,  150,  150,  150,  150,   87,
      150,  150,  150,   11,  150,    0,  152,  150,  150,  150,
      150,   19,  150,  113,  150,  150,  150,  150,  150,  150,
      150,  150,   25,  150,  114,  150,  150,  150,  150,  150,
       80,  150,  150,   64,   63,  123,  150,  150,  150,  150,
       93,  150,  150,   22,  150,  150,  150,  150,   18,  150,
      108,   92,  150,  150,  150,   12,   10,  150,  150,  150,
      150,   75,   49,  110,   50,  150,  150,  150,   76,   71,
      150,  150,  150,  150,  150,  150,  150,  150,   90,  150,
      150,   62,  150,  150,  150,  150,  150,  150,  104,  107,

      150,  150,   83,  150,  150,  150,  150,  150,  150,   97,
      150,  150,  150,   89,   72,  150,   23,  150,  150,  150,
      150,  150,  111,  115,  150,   96,    5,  150,  150,   20,
      150,   98,  150,  150,   74,   84,  106,   13,  124,  150,
      150,   56,  150,  150,  150,  150,  150,  103,  150,  150,
      150,  150,  150,  150,  150,  150,  150,  150,  150,  150,
       85,  102,  150,   73,  150,   26,   27,  150,  150,   45,
      150,   99,   46,  150,  100,  150,  101,  150,   91,  150,
       44,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    1,    1,    6,    1,    1,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       15,   15,   15,   15,   15,   15,   15,   18,    1,    1,
       19,   20,    1,   21,   22,   23,   24,   25,   26,   27,
       28,   26,   29,   26,   26,   30,   31,   32,   33,   34,
       26,   26,   35,   36,   26,   26,   37,   26,   26,   26,
       38,    1,   39,    1,   26,    1,   40,   41,   42,   43,

       44,   45,   46,   47,   48,   26,   49,   50,   51,   52,
       53,   54,   55,   56,   57,   58,   59,   60,   61,   62,
       63,   64,   65,    1,   66,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[68] =
    {   0,
        1,    1,    1,    2,    2,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    3,    3,    1,    1,    1,
        1,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    1,    1,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    1,    1,    2
    } ;

static yyconst flex_uint16_t yy_base[489] =
    {   0,
        0,    0,  568,  569,   66,  569,    0,  569,  569,  569,
      558,  569,  569,  546,   56,  551,   61,  569,  569,  561,
      538,    0,   53,    0,   50,   57,  528,    0,    0,    0,
        0,    0,  569,  569,   42,   41,   56,   48,   45,   63,
       74,   39,   66,  103,   81,   82,   82,   74,   93,  110,
      104,   71,  521,  501,   92,  569,  569,  151,  554,  569,
      569,  147,  555,  155,  160,  554,  569,    0,  531,  519,
        0,    0,    0,    0,    0,    0,  496,   26,  511,  494,
      124,  499,    0,  502,    0,  497,  508,  507,  126,  127,
      493,  156,  487,  484,  483,  489,  494,  500,  485,  488,

      489,  480,  476,  476,  474,  473,  473,    0,    0,    0,
        0,  479,   99,  467,  476,  468,  476,  472,  125,    0,
      476,  470,  471,    0,  462,  476,  462,  470,  144,  477,
      456,  459,  141,  141,  142,  458,  139,  472,  460,  454,
      454,  469,    0,  460,  464,    0,  446,  449,  462,  569,
      500,  569,  181,    0,    0,    0,    0,  457,  453,  447,
      450,  458,  455,  456,  449,  436,  441,  435,  145,  428,
      447,    0,  435,  458,  455,  446,  437,    0,  430,  430,
      432,    0,  437,  426,  418,  421,  420,    0,  426,    0,
      434,  431,    0,  157,  423,    0,    0,  422,  410,  412,

      412,  407,  415,  416,  408,    0,  412,  413,  406,  402,
      416,  416,  414,  409,  413,    0,  410,  409,  402,  408,
        0,  395,  402,    0,  402,  390,  403,  398,  400,  404,
        0,  390,  389,    0,  393,  396,  378,  386,  390,  380,
      388,  390,  387,  375,  373,  374,    0,    0,  378,  406,
      395,    0,  384,    0,  209,  366,  372,    0,  383,  365,
      363,  362,  376,    0,  365,  369,    0,  363,  147,  362,
        0,  370,  356,  359,  353,  363,  351,    0,  364,    0,
      349,    0,    0,  352,    0,  347,  359,  350,  182,  358,
      358,    0,  140,  360,  347,  345,  339,  339,  339,    0,

      342,  353,  350,    0,  328,  332,  333,  344,  339,    0,
      346,  332,  349,    0,  339,  379,  569,  276,  341,  340,
      323,    0,  338,    0,  337,  330,  323,  328,  333,  332,
      315,  184,    0,  327,    0,  316,  182,  311,  188,  309,
        0,  316,  317,    0,    0,    0,  320,  310,  303,  318,
      193,  304,  315,    0,  301,  298,  283,  294,    0,  285,
        0,    0,  291,  278,  291,    0,    0,  275,  281,  288,
      272,    0,    0,    0,    0,  278,  272,  278,    0,    0,
      283,  281,  266,  267,  278,  264,  264,  261,    0,  274,
      274,    0,  273,  255,  255,  270,  257,  258,    0,    0,

      255,  264,    0,  262,  257,  246,  259,  258,  257,    0,
      243,  245,  252,    0,    0,  236,    0,  236,  235,  225,
      216,  231,    0,    0,  226,    0,    0,  219,  225,    0,
      224,    0,  209,  223,    0,    0,    0,    0,    0,  214,
      219,    0,  209,  209,  207,  206,  200,    0,  213,  212,
      211,  197,  213,  208,  193,  194,  205,  194,  187,  185,
        0,    0,  183,    0,  179,    0,    0,  179,  185,    0,
      177,    0,    0,  111,    0,   85,    0,   64,    0,   50,
        0,  569,  343,  346,   92,  349,  352,  355
    } ;

static yyconst flex_int16_t yy_def[489] =
    {   0,
      482,    1,  482,  482,  482,  482,  483,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  484,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  482,  482,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  482,  482,  482,  483,  482,
      482,  482,  486,  482,  482,  484,  482,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,

      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  482,
      486,  482,  482,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,

      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  487,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,

      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  488,  482,  487,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,

      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,  485,  485,  485,  485,  485,  485,  485,  485,  485,
      485,    0,  482,  482,  482,  482,  482,  482
    } ;

static yyconst flex_uint16_t yy_nxt[637] =
    {   0,
        4,    5,    6,    5,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   17,   17,   18,   19,    4,
       20,   21,   22,   23,   24,   24,   25,   26,   24,   24,
       27,   28,   29,   24,   30,   31,   32,   33,   34,   35,
       36,   37,   38,   39,   40,   41,   24,   42,   43,   44,
       45,   46,   47,   48,   24,   49,   50,   51,   52,   53,
       24,   24,   54,   55,   56,   57,    4,   58,  157,   58,
       62,   62,   62,   64,   70,   65,   65,   65,   72,   74,
       81,   71,   73,   77,   78,  158,   97,   93,   82,  106,
      107,   94,   83,   75,   68,   95,   84,   85,   79,   86,

       80,  481,   87,   96,   98,   88,   99,  108,   89,   90,
      100,   91,  101,  103,   92,  102,  480,  104,  110,  111,
      114,  109,  144,  118,  145,  119,  127,  105,  115,  128,
      120,  116,  125,  126,  121,  148,  129,  122,  192,  117,
      123,  479,  112,  139,  193,  124,  130,  140,  149,  131,
      141,  132,   58,  133,   58,  113,  134,  135,  478,  142,
      143,   62,   62,   62,  136,  161,  171,  137,  138,  153,
      153,  153,   64,  162,   65,   65,   65,  169,  174,  170,
      175,  163,  199,  208,  215,  172,  200,  219,  217,  209,
      348,  222,  349,  210,  223,  153,  153,  153,  216,  218,

      211,  245,  246,  329,  330,  220,  265,  266,  267,  316,
      316,  317,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  344,  379,  384,  316,  316,  316,  316,
      385,  387,  396,  477,  476,  475,  474,  345,  473,  380,
      381,  472,  471,  397,  388,  470,  316,  316,  469,  468,
      467,  466,  465,  464,  463,  462,  461,  460,  459,  458,
      457,  456,  455,  454,  453,  452,  451,  450,  449,  448,
      447,  446,  445,  316,  316,  316,  316,  316,  317,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      444,  443,  442,  316,  316,  316,  316,  441,  440,  439,

      438,  437,  436,  435,  434,  433,  432,  431,  430,  429,
      428,  427,  426,  316,  316,  425,  424,  423,  422,  421,
      420,  419,  418,  417,  416,  415,  414,  413,  412,  411,
      410,  409,  408,  407,  406,  405,  404,  403,  402,  401,
      316,  316,  316,   59,  400,   59,   66,   66,   66,  151,
      151,  151,  318,  318,  318,  316,  316,  316,  399,  398,
      395,  394,  393,  392,  391,  390,  389,  386,  383,  382,
      378,  377,  376,  375,  374,  373,  372,  371,  370,  369,
      368,  317,  367,  366,  365,  364,  363,  362,  361,  360,
      359,  358,  357,  356,  355,  354,  353,  352,  351,  350,

      347,  346,  343,  342,  341,  340,  339,  338,  337,  336,
      335,  334,  333,  332,  331,  328,  327,  326,  325,  324,
      323,  322,  321,  320,  319,  315,  314,  313,  312,  311,
      310,  309,  308,  307,  306,  305,  304,  303,  302,  301,
      300,  299,  298,  297,  296,  295,  294,  293,  292,  291,
      290,  289,  288,  287,  286,  285,  284,  283,  282,  281,
      280,  279,  278,  277,  276,  275,  274,  273,  272,  271,
      270,  269,  268,  264,  263,  262,  261,  260,  259,  258,
      257,  256,  255,  254,  253,  252,  251,  250,  249,  248,
      247,  244,  243,  242,  241,  240,  239,  238,  237,  236,

      235,  234,  152,  233,  232,  231,  230,  229,  228,  227,
      226,  225,  224,  221,  214,  213,  212,  207,  206,  205,
      204,  203,  202,  201,  198,  197,  196,  195,  194,  191,
      190,  189,  188,  187,  186,  185,  184,  183,  182,  181,
      180,  179,  178,  177,  176,  173,  168,  167,  166,  165,
      164,  160,  159,  156,  155,  154,   67,  152,  150,  147,
      146,   76,   69,   67,   63,   61,   60,  482,    3,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,

      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482
    } ;

static yyconst flex_int16_t yy_chk[637] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    5,   78,    5,
       15,   15,   15,   17,   23,   17,   17,   17,   25,   26,
       36,   23,   25,   35,   35,   78,   39,   38,   36,   42,
       42,   38,   36,   26,  485,   38,   36,   37,   35,   37,

       35,  480,   37,   38,   39,   37,   39,   43,   37,   37,
       40,   37,   40,   41,   37,   40,  478,   41,   44,   44,
       45,   43,   52,   46,   52,   46,   48,   41,   45,   48,
       46,   45,   47,   47,   46,   55,   49,   46,  113,   45,
       46,  476,   44,   51,  113,   46,   49,   51,   55,   50,
       51,   50,   58,   50,   58,   44,   50,   50,  474,   51,
       51,   62,   62,   62,   50,   81,   90,   50,   50,   64,
       64,   64,   65,   81,   65,   65,   65,   89,   92,   89,
       92,   81,  119,  129,  133,   90,  119,  135,  134,  129,
      293,  137,  293,  129,  137,  153,  153,  153,  133,  134,

      129,  169,  169,  269,  269,  135,  194,  194,  194,  255,
      255,  255,  255,  255,  255,  255,  255,  255,  255,  255,
      255,  255,  255,  289,  332,  337,  255,  255,  255,  255,
      337,  339,  351,  471,  469,  468,  465,  289,  463,  332,
      332,  460,  459,  351,  339,  458,  255,  255,  457,  456,
      455,  454,  453,  452,  451,  450,  449,  447,  446,  445,
      444,  443,  441,  440,  434,  433,  431,  429,  428,  425,
      422,  421,  420,  255,  255,  255,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      419,  418,  416,  318,  318,  318,  318,  413,  412,  411,

      409,  408,  407,  406,  405,  404,  402,  401,  398,  397,
      396,  395,  394,  318,  318,  393,  391,  390,  388,  387,
      386,  385,  384,  383,  382,  381,  378,  377,  376,  371,
      370,  369,  368,  365,  364,  363,  360,  358,  357,  356,
      318,  318,  318,  483,  355,  483,  484,  484,  484,  486,
      486,  486,  487,  487,  487,  488,  488,  488,  353,  352,
      350,  349,  348,  347,  343,  342,  340,  338,  336,  334,
      331,  330,  329,  328,  327,  326,  325,  323,  321,  320,
      319,  316,  315,  313,  312,  311,  309,  308,  307,  306,
      305,  303,  302,  301,  299,  298,  297,  296,  295,  294,

      291,  290,  288,  287,  286,  284,  281,  279,  277,  276,
      275,  274,  273,  272,  270,  268,  266,  265,  263,  262,
      261,  260,  259,  257,  256,  253,  251,  250,  249,  246,
      245,  244,  243,  242,  241,  240,  239,  238,  237,  236,
      235,  233,  232,  230,  229,  228,  227,  226,  225,  223,
      222,  220,  219,  218,  217,  215,  214,  213,  212,  211,
      210,  209,  208,  207,  205,  204,  203,  202,  201,  200,
      199,  198,  195,  192,  191,  189,  187,  186,  185,  184,
      183,  181,  180,  179,  177,  176,  175,  174,  173,  171,
      170,  168,  167,  166,  165,  164,  163,  162,  161,  160,

      159,  158,  151,  149,  148,  147,  145,  144,  142,  141,
      140,  139,  138,  136,  132,  131,  130,  128,  127,  126,
      125,  123,  122,  121,  118,  117,  116,  115,  114,  112,
      107,  106,  105,  104,  103,  102,  101,  100,   99,   98,
       97,   96,   95,   94,   93,   91,   88,   87,   86,   84,
       82,   80,   79,   77,   70,   69,   66,   63,   59,   54,
       53,   27,   21,   20,   16,   14,   11,    3,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,

      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482,  482,  482,  482,  482,
      482,  482,  482,  482,  482,  482
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[155] =
    {   0,
0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "alex.l"
/*****************************************************************************/
/**  Lexical analyzer, 2016.                        <jmbenedi@prhlt.upv.es> **/
/*****************************************************************************/
#line 5 "alex.l"
#include <stdio.h>
#include <string.h>
#include "nettable.h"
#include "asin.h"

int verbosity=FALSE;                     /* If you want to display the trace */
int numErrores=0;                        /* Counter for number of errors     */

#define  display(x) {if (verbosity) ECHO; return x;}
void createLiteral() ;
void emiteDirective() ;
void creatececho() ;
#line 816 "alex.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 34 "alex.l"

#line 1036 "alex.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 483 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 569 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 35 "alex.l"
{ if (verbosity) ECHO;}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 36 "alex.l"
{ if (verbosity) 
                    { ECHO; fprintf(stdout,"%3d.- ", yylineno); } }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 38 "alex.l"
{ if (verbosity) 
                    { ECHO; fprintf(stdout,"%3d.- ", yylineno); } }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 41 "alex.l"
{ display(batch_);    }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 42 "alex.l"
{ display(threads_);  }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 43 "alex.l"
{ display(log_);      }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 44 "alex.l"
{ display(seed_);     }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 45 "alex.l"
{ display(cpu_);      }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 46 "alex.l"
{ display(gpu_);      }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 47 "alex.l"
{ display(device_);   }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 48 "alex.l"
{ display(cuDNN_);    }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 49 "alex.l"
{ display(cuBLAS_);   }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 51 "alex.l"
{ display(filename_);   } 
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 52 "alex.l"
{ display(tr_);         }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 53 "alex.l"
{ display(ts_);         }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 54 "alex.l"
{ display(va_);         }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 55 "alex.l"
{ display(ascii_);      }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 56 "alex.l"
{ display(binary_);     }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 57 "alex.l"
{ display(gauss_);      }   
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 58 "alex.l"
{ display(uniform_);    } 
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 59 "alex.l"
{ display(ones_);       }   
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 60 "alex.l"
{ display(zeros_);      } 
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 61 "alex.l"
{ display(oneshot_);    }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 62 "alex.l"
{ display(pos_);        } 
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 63 "alex.l"
{ display(nrows_);      } 
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 64 "alex.l"
{ display(ncolsample_); } 
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 65 "alex.l"
{ display(ncoltarget_); } 
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 66 "alex.l"
{ display(T_);          }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 67 "alex.l"
{ display(S_);          }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 68 "alex.l"
{ display(W_);          }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 69 "alex.l"
{ display(GW_);         }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 70 "alex.l"
{ display(B_);          }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 71 "alex.l"
{ display(GB_);         }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 72 "alex.l"
{ display(N_);          }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 74 "alex.l"
{ display(F_);   } 
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 75 "alex.l"
{ display(FI_);  }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 76 "alex.l"
{ display(FO_);  }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 77 "alex.l"
{ display(C_);   }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 78 "alex.l"
{ display(CI_);  }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 79 "alex.l"
{ display(MP_);  }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 80 "alex.l"
{ display(CAT_); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 81 "alex.l"
{ display(ADD_); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 82 "alex.l"
{ display(O_);   }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 84 "alex.l"
{ display(classification_); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 85 "alex.l"
{ display(regression_);     }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 86 "alex.l"
{ display(autoencoder_);    }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 87 "alex.l"
{ display(max_);            }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 88 "alex.l"
{ display(min_);            }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 89 "alex.l"
{ display(maxlog_);         }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 90 "alex.l"
{ display(minlog_);         }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 92 "alex.l"
{ display(nz_);             }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 93 "alex.l"
{ display(nr_);             }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 94 "alex.l"
{ display(nc_);             }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 95 "alex.l"
{ display(cr_);             }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 96 "alex.l"
{ display(cc_);             }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 97 "alex.l"
{ display(numnodes_);       }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 98 "alex.l"
{ display(nk_);             }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 99 "alex.l"
{ display(kr_);             }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 100 "alex.l"
{ display(kc_);             }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 101 "alex.l"
{ display(rpad_);           }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 102 "alex.l"
{ display(cpad_);           }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 103 "alex.l"
{ display(stride_);         }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 104 "alex.l"
{ display(sizer_);          }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 105 "alex.l"
{ display(sizec_);          }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 107 "alex.l"
{ display(mu_);         }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 108 "alex.l"
{ display(mmu_);        }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 109 "alex.l"
{ display(l2_);         }      
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 110 "alex.l"
{ display(l1_);         }       
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 111 "alex.l"
{ display(maxn_);       }       
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 112 "alex.l"
{ display(drop_);       }      
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 113 "alex.l"
{ display(noiser_);     }      
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 114 "alex.l"
{ display(noisesd_);    }     
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 115 "alex.l"
{ display(brightness_); }     
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 116 "alex.l"
{ display(contrast_);   }     
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 117 "alex.l"
{ display(lambda_);     } 
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 118 "alex.l"
{ display(noiseb_);     } 
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 119 "alex.l"
{ display(advf_);       } 
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 120 "alex.l"
{ display(bn_);         } 
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 121 "alex.l"
{ display(act_);        }       
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 122 "alex.l"
{ display(shift_);      }     
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 123 "alex.l"
{ display(flip_);       }     
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 124 "alex.l"
{ display(adv_);        } 
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 125 "alex.l"
{ display(balance_);    } 
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 126 "alex.l"
{ display(cropmode_);   } 
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 127 "alex.l"
{ display(trainable_);  } 
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 128 "alex.l"
{ display(for_);        } 
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 130 "alex.l"
{ display(const_);        }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 131 "alex.l"
{ display(data_);         }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 133 "alex.l"
{ display(network_);      }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 134 "alex.l"
{ display(script_);       }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 136 "alex.l"
{ display(printkernels_); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 137 "alex.l"
{ display(change_);       }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 138 "alex.l"
{ display(train_);        }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 139 "alex.l"
{ display(save_);         }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 140 "alex.l"
{ display(load_);         }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 141 "alex.l"
{ display(testout_);      }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 142 "alex.l"
{ display(forward_);      }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 143 "alex.l"
{ display(backward_);     }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 144 "alex.l"
{ display(resetstats_);   }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 145 "alex.l"
{ display(printerrors_);  }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 146 "alex.l"
{ display(reseterrors_);  }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 147 "alex.l"
{ display(trainmode_);    }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 148 "alex.l"
{ display(testmode_);     }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 149 "alex.l"
{ display(update_);       }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 150 "alex.l"
{ display(test_);         }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 151 "alex.l"
{ display(evaluate_);     }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 152 "alex.l"
{ display(zscore_);       }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 153 "alex.l"
{ display(center_);       }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 154 "alex.l"
{ display(yuv_);          }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 155 "alex.l"
{ display(maxmin_);       }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 156 "alex.l"
{ display(shuffle_);      }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 157 "alex.l"
{ display(next_);         }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 158 "alex.l"
{ display(imult_);        }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 159 "alex.l"
{ display(omult_);        }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 160 "alex.l"
{ display(sigmoid_);      }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 161 "alex.l"
{ display(tanh_);         }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 162 "alex.l"
{ display(relu_);         }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 163 "alex.l"
{ display(mul_);          }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 164 "alex.l"
{ display(set_);          }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 165 "alex.l"
{ display(div_);          }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 166 "alex.l"
{ display(add_);          }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 167 "alex.l"
{ display(sub_);          }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 168 "alex.l"
{ display(store_);        }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 169 "alex.l"
{ display(getstats_);     }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 170 "alex.l"
{ display(copy_);         }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 173 "alex.l"
{ display(bin_);          }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 174 "alex.l"
{ display(int_);          }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 175 "alex.l"
{ display(real_);         }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 176 "alex.l"
{ display(exp_);          }
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 177 "alex.l"
{ display(sqr_);          }
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 179 "alex.l"
{ display(MAS_);    }
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 180 "alex.l"
{ display(MENOS_);  }
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 181 "alex.l"
{ display(POR_);    }
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 182 "alex.l"
{ display(DIV_);    }
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 183 "alex.l"
{ display(MOD_);    }
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 184 "alex.l"
{ display(PORPOR_); }
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 185 "alex.l"
{ display(BCB_);     /* Begin Curly  Brackets */ }
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 186 "alex.l"
{ display(ECB_);     /* End   Curly  Brackets */ }
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 187 "alex.l"
{ display(BSB_);     /* Begin Square Brackets */ }
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 188 "alex.l"
{ display(ESB_);     /* End   Square Brackets */ }
	YY_BREAK
case 141:
YY_RULE_SETUP
#line 189 "alex.l"
{ display(BRB_);     /* Begin Round  Brackets */ }
	YY_BREAK
case 142:
YY_RULE_SETUP
#line 190 "alex.l"
{ display(ERB_);     /* End   Round  Brackets */ }
	YY_BREAK
case 143:
YY_RULE_SETUP
#line 191 "alex.l"
{ display(PER_);     /* period                */ }
	YY_BREAK
case 144:
YY_RULE_SETUP
#line 192 "alex.l"
{ display(COL_);     /* colon                 */ }
	YY_BREAK
case 145:
YY_RULE_SETUP
#line 193 "alex.l"
{ display(COM_);     /* comma                 */ }
	YY_BREAK
case 146:
YY_RULE_SETUP
#line 194 "alex.l"
{ display(EQ_);      /* equal                 */ }
	YY_BREAK
case 147:
YY_RULE_SETUP
#line 195 "alex.l"
{ display(RAR_);     /* rightarrow            */ }
	YY_BREAK
case 148:
/* rule 148 can match eol */
YY_RULE_SETUP
#line 197 "alex.l"
{ emiteDirective();                                 }
	YY_BREAK
case 149:
YY_RULE_SETUP
#line 198 "alex.l"
{ yylval.creal = atof(yytext);    display(cte_);    }
	YY_BREAK
case 150:
YY_RULE_SETUP
#line 199 "alex.l"
{ yylval.ident = strdup(yytext);  display(id_);     }
	YY_BREAK
case 151:
/* rule 151 can match eol */
YY_RULE_SETUP
#line 200 "alex.l"
{ createLiteral(); display(nfile_);                 }
	YY_BREAK
case 152:
/* rule 152 can match eol */
YY_RULE_SETUP
#line 201 "alex.l"
{ creatececho();   display(cecho_);                 }
	YY_BREAK
case 153:
YY_RULE_SETUP
#line 202 "alex.l"
{ yyerror("unknown character"); if (verbosity) ECHO;}
	YY_BREAK
case 154:
YY_RULE_SETUP
#line 203 "alex.l"
ECHO;
	YY_BREAK
#line 1880 "alex.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 67);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 483 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 67;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 483 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 482);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 203 "alex.l"


/*****************************************************************************/
void creatececho()
{ char *t;
  t = (char *)malloc(yyleng+1); strncpy(t, yytext, yyleng);
  t[yyleng-1] = '\0'; 
  yylval.ident = strdup(t);
  free(t);
}
/*****************************************************************************/
void createLiteral()
{ char *t; int i;
  t = (char *)malloc(yyleng-1); 
  for (i = 0; (i < yyleng-2); i++) t[i] = yytext[i+1];
  t[yyleng-2] = '\0';
  yylval.ident = strdup(t);
  free(t);
}
/*****************************************************************************/
void emiteDirective()
{ char *t; int i, l, p; 
  t = (char *)malloc(yyleng);
  for (i = 0; i < (yyleng-2); i++) t[i] = yytext[i+1]; 
  t[yyleng-2] = '\0';  
  p =  strspn(t, " \t"); l = strlen(t);
  for (i = 0; i < (l-p); i++) t[i] = t[i+p]; 
  t[l-p] = '\0'; 
  emit(t);  free(t);
}
/*****************************************************************************/

